== Module 5: Network Egress Firewall

Security is important to every customer. 
The least privilege principle is a common security practice that limits an application's access to only those resources it needs to operate. 
For example, if we know an application does not need access to the internet, we should create a policy to block that application’s access to the internet.

In the real world, customers will solve this challenge with outbound proxies/VLANs/firewalls, but those solutions can be expensive and complex to implement. 
Now we will show OpenShift Virtualization allows us to add an additional layer of security with just a few button clicks.

. Click “VirtualMachines”, click “winnetworking1” then click the “Console” tab. 
Login to the Windows VM
. Click the start menu, then type “powershell”. 
Run “curl google.com” and notice that the connection succeeds
. On the left side, click “Networking”. 
Click “NetworkPolicies”. 
Click “Create NetworkPolicy”.
. Name the policy “no-egress” then click “Add pod selector”. 
The label is App and the Selector is winnetworking
. Click the link that says “affected pods” to see the pods that will be affected by this networking policy. 
Click “Deny all egress traffic” and click “Create”.
. Go back to the powershell window and run “curl google.com” again. 
Notice that the network connection hangs indicating internet access is blocked.
